import type { LucideIcon } from "lucide-react"
import {
  AlignLeft,
  Baseline,
  Calendar,
  CheckSquare,
  ChevronDownSquare,
  Clock3,
  Code2,
  File,
  FileImage,
  Heading,
  Image,
  Link2,
  ListChecks,
  MapPin,
  Minus,
  Pilcrow,
  Rows2,
  Sigma,
  Type,
} from "lucide-react"
import type { AddableFieldType } from "./factories"

export const ELEMENT_ICON_BY_TYPE: Record<AddableFieldType, LucideIcon> = {
  headingDescriptionGroup: Rows2,
  heading: Heading,
  description: Pilcrow,
  markdown: Code2,
  divider: Minus,
  media: Image,
  pageBreak: AlignLeft,
  text: Type,
  textarea: Baseline,
  number: Sigma,
  email: Link2,
  phone: File,
  radio: ListChecks,
  checkbox: CheckSquare,
  select: ChevronDownSquare,
  file: File,
  image: FileImage,
  date: Calendar,
  time: Clock3,
  address: MapPin,
  url: Link2,
}
